### ISSUE TITLE
Create a tool for managing github issues

### ISSUE THREAD

**Issue by TheKnarf** [YakPie/ideas-for-stream#5]
Ref tsoding/snitch/issues/12 and tsoding/snitch/issues/11

Some imagined features:
```
gissue                                     # Same as "gissue help"
gissue new                                 # Opens $EDITOR to create a new issue
gissue cat ([0-9]+)                        # Prints out a single issue
gissue search "is:issue is:open"           # searches issues using githubs search query
gissue edit ([0-9]+)                       # Opens $EDITOR to edit an issue
gissue upvote ([0-9]+)                     # Adds the upvote emoji to an issue
gissue downvote ([0-9]+)                   # Adds the downvote emoji to an issue
gissue workon ([0-9]+)                     # Sets next commit message to "Work on #10"
gissue fixes ([0-9]+)                      # Sets next commit message to "Fixes #10"
gissue list                                # Lists all open issues
gissue label                               # Same as "gissue help label"
gissue label new                           # Opens $EDITOR to create a new label
gissue label list                          # Lists all labels
gissue help                                # Shows this list
gissue help label                          # Shows subcommands for label
```

**TODO**

- [ ] Create a repo for it
- [ ] Create a Readme with description taken from above
- [ ] Plan time in the calendar to build this on stream
- [ ] Move the issues from under into their own issues

**ISSUES**

- [ ] Create an empty Go application
- [ ] Setup build enviroment
- [ ] Setup Jenkins
- [ ] Choose a license
- [ ] Write an application that correctly parses command line agruments according to the plan
- [ ] Parse a config file or enviroment variable with Github OAuth token
- [ ] Implement `gissue new` functionallity
- [ ] Implement `gissue search` functionallity
- [ ] Implement `gissue workon` and `gissue fixes` functionallity

**OTHER FUNCTIONALLITY**

- Support all emojis
- Let you make comments on issues
- Let you read comments on issues
- Let you upvote / emojis on comments
- Let you assign isses, set project and milestone for issues
- Subscribe / Unsubscribe from issues
- Lock conversation
- Read the [API documentation](https://developer.github.com/v3/issues/) to see what else is possible
